name: Discord Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t discord-lua-bot .

    - name: Run Discord Bot
      run: |
        docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} discord-lua-bot