name: Run Bot

on:
  push:
    branches:
      - main  # این اکشن هنگام پوش به شاخه اصلی اجرا میشه
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # یا windows-latest، macos-latest

    steps:
    # 1. چک کردن کد
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. نصب وابستگی‌ها
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # نسخه پایتون مورد نیاز برای بات

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3. اجرای بات
    - name: Run bot
      run: |
        python bot.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # استفاده از توکن ذخیره‌شده در GitHub Secrets
